version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
      - "5432:5432"

    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
      - POSTGRE_DATABASE_USER_NAME=postgres
      - POSTGRE_DATABASE_PASSWORD=postgres
      - POSTGRE_DATABASE_NAME=typeorm_test

    network_mode: host
    # depends_on:
    #   - db

  # db:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_USER: your_postgres_user
  #     POSTGRES_PASSWORD: your_postgres_password
  #     POSTGRES_DB: your_database_name
  #   ports:
  #     - "5432:5432"
