name: CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CDK_DEFAULT_ACCOUNT: ${{ secrets.CDK_DEFAULT_ACCOUNT }}
      CDK_DEFAULT_REGION: ${{ secrets.CDK_DEFAULT_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_PROFILE: default

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm install
          cd ./aws-cdk/dependencies/layer1 && npm install

      - name: Build Nest.js app
        run: npm run build

      - name: Set up AWS credentials
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/config
          echo "region = $CDK_DEFAULT_REGION" >> ~/.aws/config
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
          echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials

      - name: Deploy with CDK
        run: |
          npm install -g aws-cdk@2.130.0
          cdk deploy --require-approval never

      - name: Clean up
        run: |
          npm prune --production
