name: CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TEST_VARIABLE: ${{ secrets.TEST_VARIABLE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Check secret
        run: |
          echo ${{ secrets.TEST_VARIABLE}}
          echo $TEST_VARIABLE

      - name: Install dependencies
        run: npm install

      - name: Build Nest.js app
        run: npm run build

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: Deploy with CDK
        run: |
          npm install -g aws-cdk@2.130.0
          cdk deploy CdkStack --require-approval never

      - name: Clean up
        run: |
          npm prune --production
